update

diff --git a/.github/workflows/create-api-client-based-on-openapi.yml b/.github/workflows/create-api-client-based-on-openapi.yml
--- a/.github/workflows/create-api-client-based-on-openapi.yml
+++ b/.github/workflows/create-api-client-based-on-openapi.yml
@@ -4,22 +4,104 @@ on:
   repository_dispatch:
     types: [send-docs]
 
-  jobs:
-    process-docs:
-      runs-on: ubuntu-latest
-      steps:
-#        - name: Checkout Repository
-#          uses: actions/checkout@v3
-        - name: Receive Documentation JSON
-          env:
-            DOCS_JSON: ${{ github.event.client_payload.docs_json }}
-          run: |
-            echo $DOCS_JSON
-#            echo "$DOCS_JSON" > docs.json
-#        - name: Commit Documentation
-#          run: |
-#            git config --local user.name "github-actions[bot]"
-#            git config --local user.email "github-actions[bot]@users.noreply.github.com"
-#            git add docs.json
-#            git commit -m "Update documentation from Repo A" || echo "No changes to commit"
-#            git push
+permissions:
+  contents: write
+
+jobs:
+  process-docs:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v3
+      - name: Receive and Persist JSON OpenAPI specs
+        env:
+          AUTHOR: ${{ github.event.client_payload.author }}
+          OPENAPI_COMPRESSED: ${{ github.event.client_payload.file_content_base_64 }}
+          app_name: ${{ github.event.client_payload.app_name }}
+          web_openapi_path: ${{ github.workspace }}/src/web/openapi_specs
+        run: |
+          author=$GITHUB_AUTHOR
+          echo "::notice:: Process triggered by $AUTHOR"
+          app_name=$(echo $app_name | sed s/-/_/g)
+          if [[ $app_name == "" ]]; then
+            echo "::error:: app_name cannot be empty"
+            exit 1
+          fi
+          openapi_filename="$app_name"_openapi_specification.json
+          openapi_filepath=$web_openapi_path/$openapi_filename
+          echo "Persisting openapi specs  in $openapi_filepath" 
+          OPENAPI=$(echo $OPENAPI_COMPRESSED | base64 -d | unxz -c)
+          echo $OPENAPI > $openapi_filepath
+          echo "----"
+          
+          echo "api_root_dir=${{ github.workspace }}/src/apis" >> $GITHUB_ENV
+          
+          echo "::notice::Update for $app_name"
+
+          echo "app_name=$app_name" >> $GITHUB_ENV
+          echo "openapi_filepath=$openapi_filepath"
+          echo "openapi_filepath=$openapi_filepath" >> $GITHUB_ENV
+          echo "openapi_filename=$openapi_filename" >> $GITHUB_ENV
+      - name: Create scaffolding & register docs
+        run: |
+          echo "api_root_dir: $api_root_dir"
+          
+          # TODO: What to do with conflict?
+          if [ ! -d $api_root_dir/$app_name ]
+          then
+            echo "::notice:: Creating dir $api_root_dir/$app_name"
+            mkdir $api_root_dir/$app_name
+          else
+            echo "API $api_root_dir/$app_name already exists."
+          fi
+          
+          # Add file to register docs into fastapi 
+          cat <<- EOF > $api_root_dir/$app_name/register_api_docs.py
+          api_id: str = '$app_name'
+          openapi_specs_name: str = '$openapi_filename'
+          docs_endpoint_name: str = '/$app_name/'
+          EOF
+
+      - name: Prepare openapi config file
+        run: |
+          config_file_path="./generator_config_file.yaml"
+          cat <<- EOF -> $config_file_path
+          generatorName: python
+          inputSpec: $openapi_filepath
+          additionalProperties:
+            packageName: $app_name
+            projectName: $app_name
+          configOptions:
+            packageVersion: "1.0.0"
+            library: fastapi
+          EOF
+          
+          if [ -d $api_root_dir/$app_name/client ]
+          then
+            echo "Deleting old client..."
+            rm -R $api_root_dir/$app_name/client
+          fi
+          
+          echo "openapi_filepath=$openapi_filepath"
+          cat $config_file_path
+          
+          echo "config_file_path=$config_file_path" >> $GITHUB_ENV
+          echo $OPENAPI > ./openapi.json
+          
+
+      - name: Generate client
+        uses: openapi-generators/openapitools-generator-action@v1
+        with:
+          generator: python
+          config-file: ${{ env.config_file_path }}
+          openapi-file: ./src/web/openapi_specs/${{ env.openapi_filename }}
+          command-args: "-o ./src/apis/${{ env.app_name }}/client"
+
+      - name: Persist changes with Git
+        run: |
+          echo "Commiting dir $api_root_dir/$app_name"
+          git config --local user.name "fetchbot"
+          git config --local user.email "fetchbot@fetch.ai"
+          git add $api_root_dir/$app_name ${{ github.workspace }}/src/web/
+          git commit -m "Adding or updating docs and client for $app_name" || echo "No changes to commit"
+          git push
